//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSL.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSL.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        public static string ActivityDetails_Calories {
            get {
                return ResourceManager.GetString("ActivityDetails_Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string ActivityDetails_Location {
            get {
                return ResourceManager.GetString("ActivityDetails_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ActivityDetails_Name {
            get {
                return ResourceManager.GetString("ActivityDetails_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        public static string ActivityDetails_Sport {
            get {
                return ResourceManager.GetString("ActivityDetails_Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time.
        /// </summary>
        public static string ActivityDetails_Time {
            get {
                return ResourceManager.GetString("ActivityDetails_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athlete.
        /// </summary>
        public static string AthleteDetails_Athlete {
            get {
                return ResourceManager.GetString("AthleteDetails_Athlete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        public static string AthleteDetails_Calories {
            get {
                return ResourceManager.GetString("AthleteDetails_Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string AthleteDetails_Date {
            get {
                return ResourceManager.GetString("AthleteDetails_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FitLog SportTracks (*.fitlog)|*.fitlog.
        /// </summary>
        public static string AthleteDetails_FitlogFilter {
            get {
                return ResourceManager.GetString("AthleteDetails_FitlogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported {0} activities.
        /// </summary>
        public static string AthleteDetails_ImportDonePlural {
            get {
                return ResourceManager.GetString("AthleteDetails_ImportDonePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported {0} activity.
        /// </summary>
        public static string AthleteDetails_ImportDoneSingular {
            get {
                return ResourceManager.GetString("AthleteDetails_ImportDoneSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention, {0} duplicates where not imported..
        /// </summary>
        public static string AthleteDetails_ImportDuplicatesFound {
            get {
                return ResourceManager.GetString("AthleteDetails_ImportDuplicatesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import is running....
        /// </summary>
        public static string AthleteDetails_ImportIsRunning {
            get {
                return ResourceManager.GetString("AthleteDetails_ImportIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string AthleteDetails_Location {
            get {
                return ResourceManager.GetString("AthleteDetails_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AthleteDetails_Name {
            get {
                return ResourceManager.GetString("AthleteDetails_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        public static string AthleteDetails_Sport {
            get {
                return ResourceManager.GetString("AthleteDetails_Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string General_Cancel {
            get {
                return ResourceManager.GetString("General_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string General_OK {
            get {
                return ResourceManager.GetString("General_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please match sports label from imported file with OpenSportsLog sports.
        /// </summary>
        public static string Import_PleaseMatchSports {
            get {
                return ResourceManager.GetString("Import_PleaseMatchSports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved.
        /// </summary>
        public static string MainWindow_DataSaved {
            get {
                return ResourceManager.GetString("MainWindow.DataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string MainWindow_DataSavedHeader {
            get {
                return ResourceManager.GetString("MainWindow.DataSavedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting activities....
        /// </summary>
        public static string MainWindow_DeletingActivitiesProgressMessage {
            get {
                return ResourceManager.GetString("MainWindow_DeletingActivitiesProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file....
        /// </summary>
        public static string MainWindow_LoadingFile {
            get {
                return ResourceManager.GetString("MainWindow_LoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to quit application?.
        /// </summary>
        public static string MainWindow_QuitConfirm {
            get {
                return ResourceManager.GetString("MainWindow_QuitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit confirmation.
        /// </summary>
        public static string MainWindow_QuitConfirmHeader {
            get {
                return ResourceManager.GetString("MainWindow_QuitConfirmHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving file....
        /// </summary>
        public static string MainWindow_SavingFileProgressMessage {
            get {
                return ResourceManager.GetString("MainWindow.SavingFileProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLite (*.db,*.sqlite,*.sqlite3)|*.db;*.sqlite;*.sqlite3.
        /// </summary>
        public static string MainWindow_SQLiteFilter {
            get {
                return ResourceManager.GetString("MainWindow_SQLiteFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work in progress....
        /// </summary>
        public static string MainWindow_WorkInProgress {
            get {
                return ResourceManager.GetString("MainWindow_WorkInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete selected activities.
        /// </summary>
        public static string Menu_Activities_Delete {
            get {
                return ResourceManager.GetString("Menu_Activities_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Activities.
        /// </summary>
        public static string Menu_Activity {
            get {
                return ResourceManager.GetString("Menu_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string Menu_File_New {
            get {
                return ResourceManager.GetString("Menu_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New _Athlete.
        /// </summary>
        public static string Menu_File_NewAthlete {
            get {
                return ResourceManager.GetString("Menu_File_NewAthlete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string Menu_File_Open {
            get {
                return ResourceManager.GetString("Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string Menu_File_Save {
            get {
                return ResourceManager.GetString("Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import.
        /// </summary>
        public static string Menu_Import {
            get {
                return ResourceManager.GetString("Menu_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _FitLog (SportTracks).
        /// </summary>
        public static string Menu_Import_Fitlog {
            get {
                return ResourceManager.GetString("Menu_Import_Fitlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New athlete name.
        /// </summary>
        public static string NewAthleteDialog_Name {
            get {
                return ResourceManager.GetString("NewAthleteDialog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Athlete.
        /// </summary>
        public static string NewAthleteDialog_Title {
            get {
                return ResourceManager.GetString("NewAthleteDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait....
        /// </summary>
        public static string SpinnerDialog_Title {
            get {
                return ResourceManager.GetString("SpinnerDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        public static string SpinnerDialog_Waiting {
            get {
                return ResourceManager.GetString("SpinnerDialog_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected activities.
        /// </summary>
        public static string Toolbar_DeleteSelectedActivities {
            get {
                return ResourceManager.GetString("Toolbar_DeleteSelectedActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit OSL.
        /// </summary>
        public static string Toolbar_Exit {
            get {
                return ResourceManager.GetString("Toolbar_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File.
        /// </summary>
        public static string Toolbar_New {
            get {
                return ResourceManager.GetString("Toolbar_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string Toolbar_Open {
            get {
                return ResourceManager.GetString("Toolbar_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        public static string Toolbar_Save {
            get {
                return ResourceManager.GetString("Toolbar_Save", resourceCulture);
            }
        }
    }
}
